inherit_gem:
  netsoft-rubocop:
    - config/default.yml

AllCops:
  TargetRubyVersion: 2.5

Style/SignalException:
  Exclude:
    - Dangerfile

Style/IfUnlessModifier:
  Exclude:
    - Dangerfile

Style/SoleNestedConditional:
  Exclude:
    - Dangerfile

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - Dangerfile

Layout/LineLength:
  Exclude:
    - Dangerfile

Performance/StringInclude:
  Exclude:
    - Dangerfile

