name: Install dependecies

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.8
        bundler-cache: true
        bundler: 2.3.9
        cache-version: 1.1
