name: Run tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

env:
  BUNDLE_PATH: vendor/bundle
  RAILS_ENV: test
  RUBYOPT: '-KU -E utf-8:utf-8'

jobs:
  backend:
    name: Rubocop
    runs-on: [self-hosted, linux, x64, small]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/workflows/composite-actions/dependencies

      - name: Cache Rubocop
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/rubocop_cache
          key: netsoft-danger-rubocop-${{ hashFiles('.rubocop.yml') }}
          restore-keys: |
            netsoft-danger-rubocop-${{ hashFiles('.rubocop.yml') }}
            netsoft-danger-rubocop-

      - name: Rubocop
        shell: bash
        run: |
          bundle exec rubocop -P -f progress

  danger:
    name: Run danger
    if: |
      github.event_name == 'pull_request' 
      && always()
    needs: [backend]
    runs-on: [self-hosted, linux, x64, small]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/workflows/composite-actions/dependencies

      - name: Build Danger
        shell: bash
        run: |
          gem build *.gemspec

      - name: Run danger
        shell: bash
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: |
          bundle exec danger
