name: netsoft-danger-main

on:
  pull_request:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+.[0-9a-z]+
      - v[0-9]+.[0-9]+.[0-9]+

env:
  BUNDLE_PATH: vendor/bundle
  RAILS_ENV: test
  RUBYOPT: '-KU -E utf-8:utf-8'

jobs:
  backend:
    name: Rubocop
    runs-on: [self-hosted, ubuntu-t3.medium]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # "cache-version" for the "ruby/setup-ruby" step should be bumped every time
      # apt dependencies change
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get -yq --no-install-recommends install \
            build-essential

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8
          bundler-cache: true
          bundler: 2.3.9
          cache-version: 1.0

      - uses: actions/cache@v3
        with:
          path: $HOME/.cache/rubocop_cache
          key: netsoft-danger-rubocop-${{ hashFiles('.rubocop.yml') }}
          restore-keys: |
            netsoft-danger-rubocop-${{ hashFiles('.rubocop.yml') }}
            netsoft-danger-rubocop-

      - name: Rubocop
        shell: bash
        run: |
          bundle exec rubocop -P -f progress

  publish:
    name: Publish
    if: |
      github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    needs: [ backend ]
    runs-on: [self-hosted, ubuntu-t3.medium]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8
          bundler-cache: true
          bundler: 2.3.9
          cache-version: 1.0

      - name: Get Tag Name
        id: tag_name
        shell: bash
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Tag Name Validation
        shell: bash
        env:
          SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
        run: |
          [ -z "$SOURCE_TAG" ] && { echo "Tag is empty"; exit 1;}
          echo "We are on tag: [ ${SOURCE_TAG} ]"

      - name: VERSION Validation
        shell: bash
        env:
          SOURCE_TAG: ${{ steps.tag_name.outputs.SOURCE_TAG }}
        run: |
          version=$(grep VERSION lib/netsoft-danger/version.rb | sed -e "s/.*'\([^']*\)'.*/\1/")
          [[ "v$version" == "$SOURCE_TAG" ]] && { echo "VERSION $version matches $SOURCE_TAG"; exit 0; }
          [[ "v$version" != "$SOURCE_TAG" ]] && { echo "VERSION $version does not match $SOURCE_TAG"; exit 2; }

      - name: Release Gem
        shell: bash
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
        run: |
          ./bin/setup-rubygems.sh
           rm -rf pkg
           rake build
           gem push pkg/*.gem

  danger:
    name: Run danger
    if: |
      github.event_name == 'pull_request' && always()
    needs: [ backend ]
    runs-on: [self-hosted, ubuntu-t3.medium]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.8
          bundler-cache: true
          bundler: 2.3.9
          cache-version: 1.0

      - name: Build Danger
        shell: bash
        run: |
          gem build *.gemspec

      - name: Run danger
        shell: bash
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: |
          bundle exec danger
